### PR TITLE
ApolloClient 2.0 update

### PR DESCRIPTION
**Pull request by heymartinadams**
ApolloClient is contained in 'apollo-client' package, not 'react-apollo'

### CODE REVIEW

**Comment by heymartinadams** [comment]
The code I inserted works on my end (for an unrelated app), but haven’t tested it as part of this example, @nikolasburk. May also be overkill (e.g. no subscriptions needed).

**Comment by heymartinadams** [comment]
@nikolasburk GitHub says **Changes requested**—does that mean you added specific code you need me to review and approve, or does it only mean you’re waiting for me to make changes on my own?

Still finding my way around GitHub interface.

**Comment by heymartinadams** [comment]
@nikolasburk Just made changes that should work (though again, haven’t tested): https://github.com/graphcool-examples/react-graphql/pull/58/commits/c8e2d3c5b8a43fdeaa3b93a10a83fd2e59b7c925

**Comment by nikolasburk** [comment]
Thanks a lt for the changes and apologies for the delay! We actually migrated the repo and removed the examples you proposed the changes for. Thanks anyways and please feel free to open more PRs in the future!! 👍

**Pull request closed without merging**
